name: Go Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Golang Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Go 1.24.0
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Clean Go module cache
        run: go clean -modcache

      - name: Configure Git for Private Modules
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
      
      - name: Set Go Environment for Private Modules
        run: |
          echo "GOPRIVATE=github.com/SendHive" >> $GITHUB_ENV
          go env -w GOPRIVATE=github.com/SendHive

      - name: Enable Go modules
        run: go env -w GO111MODULE=on
  
      - name: Install dependencies
        run: go mod tidy

      - name: Download dependencies
        run: go mod download

      - name: Build the project
        run: go build ./...

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: golangci-lint run --allow-parallel-runners -v
